travis:
  secure:
    BINSTAR_TOKEN: pY8/HFNAAJoV0FiGuoTY7ADcAmfmy22GYzD2xR57uOo85Vk9HPcfLRqe3CfKfOZ41TKpxQxVR7ZYXN5E1qrT5vpu15FX+1bC0c6ORZ5bPdXtBCj+1AsIitKMKGE8WNUvf1wbx784vtk7zJ09nrcXRLON3pkzUe31tPy32CPFsWrUtqi+LFfuo+M4gNEdIbYZD+qXObW3LnWUV9AZimvBHNwfPTAkMy1Xg+zwyYCNz0KjMl5iZIgpVsJf7tRBJjPvswqW/FPWUEbSiQzMp9O9nO2lMtex/evVjbbHyANIswd4c7+9KGDNAoWsJhfesUQ81bIGu8+NwRnlnh1bt2aQDfcThcLkD2qeud94ujo4N8lbr9JTUz1CFhaoUKCxijITZjf9ShhAMz4SvQeCVR4MEFRqnHEyS0NZfG9icsLx3C6378KW1bnU8vgvGldMJfoH+59Zo2TBu84kRFv97aVWHK7bdVLWDYBYyf7PQiZR+62cXN4Xj3Z8UcW6O1x8d1jQRR1X7OE7iKx1jddz+o4MQ7LnsHIPpb5nRBZEOM7dPPYIs6SjSKfGoK7k+GrtEapN86y+nZDM71e9xt0/SzHd/GLkmrErxTmZQ0LO25ayxJgP/cmyJ+BVKpT8Cdna3i4P89o9Kc7n0+937sJ4tag+U71pU4C6e5CG7Qwvyf8IhIA=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
